<h1 style="color:#6a9fb5;">Data Extraction</h1>

In [1]:
import pandas as pd
file_path = "/Users/selinwork/Documents/Ironhack/Ironhack_Week_9/Kaggle_Ok_Cupid/okcupid_profiles.csv"
dataset = pd.read_csv(file_path)

In [2]:
df = dataset.copy()

<h1 style="color:#6a9fb5;">Understanding the Dataset</h1>

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.sample(10)

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,last_online,location,offspring,pets,religion,sign,smokes,speaks,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
36115,24,single,f,straight,curvy,NaN,socially,NaN,graduated from college/university,white,66.0,-1,sales / marketing / biz dev,2012-06-09-16-45,"san francisco, california",NaN,NaN,catholicism and somewhat serious about it,virgo but it doesn&rsquo;t matter,no,english,i'm a san francisco native who loves the giant...,online video ad sales,NaN,my pearly whites,"music: arcade fire, foster the people, kings o...","family, friends, sf giants, music, the gym and...",NaN,being awesome,ask me and i'll tell you,"you're easy going, can joke around and like to..."
51069,33,single,f,straight,a little extra,NaN,socially,NaN,college/university,NaN,66.0,-1,computer / hardware / software,2012-06-28-23-44,"san francisco, california",NaN,likes dogs and has cats,agnosticism and somewhat serious about it,capricorn but it doesn&rsquo;t matter,sometimes,english,"sarcastic to a fault (the rest, is less easily...","life is a motherfuckingly awesome endeavor, i'...",finding the funny in anything navigating old s...,i'm probably smiling or laughing my eyes are g...,"books (i read a lot, so this list is filled wi...",friends movies books friends with good stories...,"how people & things work you know, a healthy m...",dinner with friends (either home cooked or out...,i invented an antm drinking game i'm a sucker ...,you have questions. i promise to do my best at...
11667,34,single,m,straight,athletic,NaN,socially,NaN,graduated from college/university,white,66.0,-1,hospitality / travel,2012-06-30-10-23,"san francisco, california",NaN,NaN,NaN,cancer,NaN,english (fluently),"i enjoy spending time at the beach, hiking in ...","working hard, and enjoying every moment of life",anything i put my mind to,my eyes and smile,"listen to a wide range of music, but i'm a big...","*family, friends *the beach/ocean *scuba divin...",what tomorrow has to offer me!,"either at home enjoying a nice glass of wine, ...",people tell me all the time that i sound like ...,you're fun and like to keep life exciting.
27100,26,single,f,straight,curvy,NaN,socially,NaN,graduated from masters program,white,64.0,-1,science / tech / engineering,2012-06-25-22-46,"san francisco, california",NaN,NaN,judaism,NaN,no,"english, german (fluently), hebrew (fluently),...","born israeli, raised in germany, and most rece...",i've straddled the fence between investing in ...,busting out in song... randomly... for no reas...,"i would say the british accent, but that's too...",NaN,NaN,NaN,NaN,NaN,... you like your sarcasm chased by a shot of ...
14555,64,single,m,straight,average,mostly anything,rarely,NaN,graduated from masters program,white,71.0,-1,other,2012-06-21-18-26,"berkeley, california",doesn't have kids,likes dogs,agnosticism but not too serious about it,sagittarius but it doesn&rsquo;t matter,no,"english (fluently), spanish (okay)",by nature i am far more interested in ways of ...,"life has been passionate, purposeful, and adve...",i'm really good at stripping away the politica...,i am told that my first impression is attentiv...,the most recommended books are: james p. carse...,good friends foreign travel and exotic food pa...,how does one build sustainable virtual and phy...,"i love to dance and favor conscious events, bu...","as a self criticism, if your politics are righ...","message me if you are fun loving, affectionate..."
48276,26,single,f,straight,fit,mostly vegan,socially,sometimes,graduated from college/university,white,64.0,-1,NaN,2011-08-28-14-09,"oakland, california",NaN,has dogs,agnosticism but not too serious about it,cancer but it doesn&rsquo;t matter,no,english,NaN,working at a restaurant working for a farm con...,NaN,NaN,NaN,my bike my dog my friends my family the outdoo...,what are we doing with our lives? daydreaming ...,NaN,NaN,NaN
47138,48,single,m,straight,fit,mostly anything,NaN,never,working on college/university,"asian, pacific islander",70.0,-1,medicine / health,2012-06-29-00-50,"san francisco, california",has kids,likes dogs,other,taurus,no,"english, chinese","i am kind, caring, loving, open minded, down t...",remain teachable...love the earth and sun and ...,being present and a good listener,calm and relaxed kind a person that goes with ...,"beautiful boy, the town, cleaner, walking dead...","family, friends, laughing, music, meditation, ...","helping others, love and peace on earth","out with friends, dancing, live music, movies ...",tell you in person,NaN
3716,31,single,m,straight,athletic,NaN,rarely,never,graduated from high school,"black, other",70.0,-1,NaN,2012-06-10-02-06,"hayward, california",NaN,NaN,NaN,NaN,trying to quit,english,swagg ..!!! big fun... love to have a good tim...,"i can say i'm doing aight, for myself. work fo...",i'm really good at ..just been myself.!!,"is my dimples, my nice smile .!","movies juice, belly sarah marshall, kevin hart...","chap stick, tooth brush, phone, grape kool- ai...",when can i get my peoples come out to the west...,hang out wit some friends..!!,NaN,1 positive attuide 2 have fun 3 enjoy life !!
37212,27,single,f,straight,athletic,anything,socially,never,graduated from masters program,NaN,71.0,-1,education / academia,2012-06-28-18-17,"san francisco, california",doesn't have kids,likes dogs and likes cats,agnosticism and laughing about it,taurus but it doesn&rsquo;t matter,no,english,"outgoing, athletic, selectively spontaneous (i...",learning and moving up!,stand up paddle board - like really good at th...,"how tall i am, though it gets pointed out less...","books: everything is illuminated, the stranger...",cereal artichokes sans worms zip up fleeces so...,how to get food for free,drinking wine with friends or being someone's ...,is that i wear lululemon to the bars sometimes,"you want to hang out with me! i'm fun, care a ..."
17516,30,single,m,gay,athletic,mostly anything,socially,never,graduated from med school,asian,68.0,-1,NaN,2012-03-27-22-26,"san francisco, california",NaN,NaN,NaN,NaN,no,english,"smart, sarcastic, fun-loving, fiercely loyal, ...","enjoying my residency program at kaiser sf, bu...","eating, tennis, zumba...not necessarily in tha...",my calves...,"books: working on sex, drugs and cocoa puffs a...",my family my friends time to work out time to ...,the future. the schooling part is just about o...,hmmm....depends on what friday night. ranges f...,i'm a romantic at heart... the old school kind...,you're looking for - real conversation - a tru...

In [5]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns)

Dataset Shape: (59946, 31)

Columns:
Index(['age', 'status', 'sex', 'orientation', 'body_type', 'diet', 'drinks',
       'drugs', 'education', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'pets', 'religion', 'sign',
       'smokes', 'speaks', 'essay0', 'essay1', 'essay2', 'essay3', 'essay4',
       'essay5', 'essay6', 'essay7', 'essay8', 'essay9'],
      dtype='object')

In [6]:
df['essay0'][0]

"about me:  i would love to think that i was some some kind of intellectual: either the dumbest smart guy, or the smartest dumb guy. can't say i can tell the difference. i love to talk about ideas and concepts. i forge odd metaphors instead of reciting cliches. like the simularities between a friend of mine's house and an underwater salt mine. my favorite word is salt by the way (weird choice i know). to me most things in life are better as metaphors. i seek to make myself a little better everyday, in some productively lazy way. got tired of tying my shoes. considered hiring a five year old, but would probably have to tie both of our shoes... decided to only wear leather shoes dress shoes.  about you:  you love to have really serious, really deep conversations about really silly stuff. you have to be willing to snap me out of a light hearted rant with a kiss. you don't have to be funny, but you have to be able to make me laugh. you should be able to bend spoons with your mind, and telepathically make me smile while i am still at work. you should love life, and be cool with just letting the wind blow. extra points for reading all this and guessing my favorite video game (no hints given yet). and lastly you have a good attention span."

<h1 style="color:#6a9fb5;">Data Cleaning</h1>

In [7]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
age                0
status             0
sex                0
orientation        0
body_type       5296
diet           24395
drinks          2985
drugs          14080
education       6628
ethnicity       5680
height             3
income             0
job             8198
last_online        0
location           0
offspring      35561
pets           19921
religion       20226
sign           11056
smokes          5512
speaks            50
essay0          5488
essay1          7572
essay2          9638
essay3         11476
essay4         10537
essay5         10850
essay6         13771
essay7         12451
essay8         19225
essay9         12603
dtype: int64

In [8]:
columns_to_drop = ['diet', 'ethnicity', 'last_online', 'location', 'religion', 'sign','pets']
columns_to_drop = [col for col in columns_to_drop if col in df.columns]
df.drop(columns=columns_to_drop, inplace=True)

In [9]:
categories = df.orientation.unique()
print(categories)

['straight' 'bisexual' 'gay']

In [10]:
def merge_gender_orientation(row):
    if row['orientation'] in ['gay', 'bisexual']:
        return 'other'
    return row['sex']

# Creating a new column 
df['gender'] = df.apply(merge_gender_orientation, axis=1)

# Dropping the sex and orientation columns
df = df.drop(['sex','orientation'], axis=1)

print(df['gender'].value_counts())

gender
m        31073
f        20533
other     8340
Name: count, dtype: int64

In [11]:
# Identifying non-integer columns
non_integer_columns = df.select_dtypes(exclude=['int64', 'float64']).columns

# Replacing NaN values in non-integer columns with "no comment"
df[non_integer_columns] = df[non_integer_columns].fillna("no comment")

# Verify that NaN values are replaced
print(df[non_integer_columns].isnull().sum())

status       0
body_type    0
drinks       0
drugs        0
education    0
job          0
offspring    0
smokes       0
speaks       0
essay0       0
essay1       0
essay2       0
essay3       0
essay4       0
essay5       0
essay6       0
essay7       0
essay8       0
essay9       0
gender       0
dtype: int64

In [12]:
print(df['status'].value_counts())

status
single            55697
seeing someone     2064
available          1865
married             310
unknown              10
Name: count, dtype: int64

In [13]:
print(df['body_type'].value_counts())

body_type
average           14652
fit               12711
athletic          11819
no comment         5296
thin               4711
curvy              3924
a little extra     2629
skinny             1777
full figured       1009
overweight          444
jacked              421
used up             355
rather not say      198
Name: count, dtype: int64

In [14]:
print(df['drugs'].value_counts())

drugs
never         37724
no comment    14080
sometimes      7732
often           410
Name: count, dtype: int64

In [15]:
print(df['education'].value_counts())

education
graduated from college/university    23959
graduated from masters program        8961
no comment                            6628
working on college/university         5712
working on masters program            1683
graduated from two-year college       1531
graduated from high school            1428
graduated from ph.d program           1272
graduated from law school             1122
working on two-year college           1074
dropped out of college/university      995
working on ph.d program                983
college/university                     801
graduated from space camp              657
dropped out of space camp              523
graduated from med school              446
working on space camp                  445
working on law school                  269
two-year college                       222
working on med school                  212
dropped out of two-year college        191
dropped out of masters program         140
masters program                        136
dropped out of ph.d program            127
dropped out of high school             102
high school                             96
working on high school                  87
space camp                              58
ph.d program                            26
law school                              19
dropped out of law school               18
dropped out of med school               12
med school                              11
Name: count, dtype: int64

In [16]:
def simplify_education(education):
    if "high school" in education:
        return "High School"
    elif "college/university" in education or "two-year college" in education:
        return "College"
    elif "masters" in education:
        return "Masters"
    elif "ph.d" in education:
        return "Ph.D."
    elif "law school" in education or "med school" in education:
        return "Professional"
    else:
        return "Other"  # Includes Space Camp and other rare categories

# Apply the function to the education column
df['education_simplified'] = df['education'].apply(simplify_education)

# Drop the original column if no longer needed
df = df.drop(['education'], axis=1)

# Check the new simplified column
print(df['education_simplified'].value_counts())

education_simplified
College         34485
Masters         10920
Other            8311
Ph.D.            2408
Professional     2109
High School      1713
Name: count, dtype: int64

In [17]:
print(df['income'].value_counts())

income
-1          48442
 20000       2952
 100000      1621
 80000       1111
 30000       1048
 40000       1005
 50000        975
 60000        736
 70000        707
 150000       631
 1000000      521
 250000       149
 500000        48
Name: count, dtype: int64

In [18]:
print(df['job'].value_counts())

job
no comment                           8198
other                                7589
student                              4882
science / tech / engineering         4848
computer / hardware / software       4709
artistic / musical / writer          4439
sales / marketing / biz dev          4391
medicine / health                    3680
education / academia                 3513
executive / management               2373
banking / financial / real estate    2266
entertainment / media                2250
law / legal services                 1381
hospitality / travel                 1364
construction / craftsmanship         1021
clerical / administrative             805
political / government                708
rather not say                        436
transportation                        366
unemployed                            273
retired                               250
military                              204
Name: count, dtype: int64

In [19]:
print(df['offspring'].value_counts())

offspring
no comment                                 35561
doesn't have kids                           7560
doesn't have kids, but might want them      3875
doesn't have kids, but wants them           3565
doesn't want kids                           2927
has kids                                    1883
has a kid                                   1881
doesn't have kids, and doesn't want any     1132
has kids, but doesn't want more              442
has a kid, but doesn't want more             275
has a kid, and might want more               231
wants kids                                   225
might want kids                              182
has kids, and might want more                115
has a kid, and wants more                     71
has kids, and wants more                      21
Name: count, dtype: int64

In [20]:
def kids(offspring):
    if "doesn't have kids" in offspring:
        return "No Kids"
    elif "has kids" in offspring or "has a kid" in offspring:
        return "Has Kids"
    elif "wants kids" in offspring or "might want kids" in offspring:
        return "Wants Kids"
    elif "doesn't want kids" in offspring:
        return "Doesn't Want Kids"
    else:
        return "No Comment"

# Apply the function to the offspring column
df['kids'] = df['offspring'].apply(kids)

# Drop the original column if no longer needed
df = df.drop(['offspring'], axis=1)

# Check the new simplified column
print(df['kids'].value_counts())

kids
No Comment           35561
No Kids              16132
Has Kids              4919
Doesn't Want Kids     2927
Wants Kids             407
Name: count, dtype: int64

In [21]:
print(df['smokes'].value_counts())

smokes
no                43896
no comment         5512
sometimes          3787
when drinking      3040
yes                2231
trying to quit     1480
Name: count, dtype: int64

In [22]:
def smoking(smokes):
    if smokes in ['no', 'no comment']:
        return "Non-Smoker"
    elif smokes in ['sometimes', 'when drinking']:
        return "Occasional Smoker"
    elif smokes == 'yes':
        return "Regular Smoker"
    elif smokes == 'trying to quit':
        return "Quitting Smoker"
    else:
        return "Unknown"  # In case of unexpected values

# Apply the function to the smokes column
df['smoking'] = df['smokes'].apply(smoking)

# Drop the original column if no longer needed
df = df.drop(['smokes'], axis=1)

# Check the new simplified column
print(df['smoking'].value_counts())

smoking
Non-Smoker           49408
Occasional Smoker     6827
Regular Smoker        2231
Quitting Smoker       1480
Name: count, dtype: int64

In [23]:
print(df['speaks'].value_counts())

speaks
english                                                                21828
english (fluently)                                                      6628
english (fluently), spanish (poorly)                                    2059
english (fluently), spanish (okay)                                      1917
english (fluently), spanish (fluently)                                  1288
                                                                       ...
english (fluently), urdu (poorly), japanese (poorly), french (okay)        1
english, spanish, hindi, c++                                               1
english (fluently), japanese (okay), thai (okay), chinese (poorly)         1
english (fluently), french (okay), italian (okay), hebrew (okay)           1
english (fluently), french, farsi                                          1
Name: count, Length: 7648, dtype: int64

In [24]:
def simplify_languages(speaks):
    if pd.isna(speaks):
        return "Unknown"
    
    # Split the languages and fluency levels
    languages = speaks.lower().split(", ")
    
    # Identify fluently spoken languages
    fluent_languages = [lang for lang in languages if "fluently" in lang]
    
    # Categorize based on the number of fluent languages
    if len(fluent_languages) == 1 and "english" in fluent_languages[0]:
        return "English Fluent Only"
    elif len(fluent_languages) == 2:
        return "Bilingual Fluent"
    elif len(fluent_languages) >= 3:
        return "Multilingual Fluent"
    elif any("english" in lang and ("poorly" in lang or "okay" in lang) for lang in languages):
        return "Basic English Speaker"
    else:
        return "Unknown"

# Apply the function to the speaks column
df['language'] = df['speaks'].apply(simplify_languages)

# Drop the original column if no longer needed
df = df.drop(['speaks'], axis=1)

# Check the new language_category column
print(df['language'].value_counts())

language
Unknown                  29949
English Fluent Only      20404
Bilingual Fluent          6977
Basic English Speaker     1593
Multilingual Fluent       1023
Name: count, dtype: int64

In [25]:
essay_column_mapping = {
    'essay0': 'self_summary',
    'essay1': 'life_work',
    'essay2': 'skills',
    'essay3': 'first_notice',
    'essay4': 'favorites',
    'essay5': 'cant_live_without',
    'essay6': 'thinking_about',
    'essay7': 'friday_night',
    'essay8': 'private_admission',
    'essay9': 'message_me_if'
}

# Rename the columns in the dataset
df.rename(columns=essay_column_mapping, inplace=True)

In [26]:
df.rename(columns={'education_simplified': 'education'}, inplace=True)

In [27]:
# Check the updated column names
print(df.columns)

Index(['age', 'status', 'body_type', 'drinks', 'drugs', 'height', 'income',
       'job', 'self_summary', 'life_work', 'skills', 'first_notice',
       'favorites', 'cant_live_without', 'thinking_about', 'friday_night',
       'private_admission', 'message_me_if', 'gender', 'education', 'kids',
       'smoking', 'language'],
      dtype='object')

In [29]:
# Define the desired column order
column_order = [
    # Profile Information
    'gender', 'status', 'age', 'height', 'body_type', 'education','income', 'kids', 'smoking','drinks','drugs', 'language','job',

    # Essays
    'self_summary', 'life_work', 'skills', 'first_notice', 'favorites',
    'cant_live_without', 'thinking_about', 'friday_night', 'private_admission', 'message_me_if',
       
]

# Reorder the dataset
df = df[column_order]

# Check the new column order
df.head()

,gender,status,age,height,body_type,education,income,kids,smoking,drinks,drugs,language,job,self_summary,life_work,skills,first_notice,favorites,cant_live_without,thinking_about,friday_night,private_admission,message_me_if
0,m,single,22,75.0,a little extra,College,-1,No Kids,Occasional Smoker,socially,never,Unknown,transportation,about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,m,single,35,70.0,average,Other,80000,No Kids,Non-Smoker,often,sometimes,English Fluent Only,hospitality / travel,i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,no comment,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,no comment,no comment,i am very open and will share just about anyth...,no comment
2,m,available,38,68.0,thin,Masters,-1,No Comment,Non-Smoker,socially,no comment,Unknown,no comment,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,no comment,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,m,single,23,71.0,thin,College,20000,Doesn't Want Kids,Non-Smoker,socially,no comment,Unknown,student,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",no comment,cats and german philosophy,no comment,no comment,you feel so inclined.
4,m,single,29,66.0,athletic,College,-1,No Comment,Non-Smoker,socially,never,Unknown,artistic / musical / writer,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",no comment,no comment,no comment,no comment,no comment

In [30]:
df.to_csv('cleaned_dataset.csv', index=False)